### ISSUE TITLE
/favoriten Route

### ISSUE THREAD

**Issue by SachsAlex** [matze328/Team1_Projekt_React#17]
- NUR bei erfolgreicher Anmeldung oder als Gast
- zur Favoriten Seite weiterleiten (OnClickEvent bei Favoriten Icon)
- zurück zu /home über App Icon

**Comment by banu-i** [comment]
- Route angelegt; Onclick Event wird noch besprochen und aufgesetzt - daher "in Progress"
 - UseState / UseContext mit TA/Kevin in Klärung -> Feedback
