### ISSUE TITLE
SocialMedia Links

### ISSUE THREAD

**Issue by SachsAlex** [matze328/Team1_Projekt_React#19]
- zur X/Instagram/Facebook Seite weiterleiten (OnClickEvent bei Social Media Icons)
- Dummy Webseite als Social Media Seite aufsetzen (minimal)
- zurück zu /home nicht erforderlich (optional als Funktion/Link möglich)

**Comment by matze328** [comment]
erledigt muss nur noch abgenommen werden und die Git Branch SocialMedia in den Main geladen werden
