### ISSUE TITLE
/login Route Funktionalität hinzufügen

### ISSUE THREAD

**Issue by SachsAlex** [matze328/Team1_Projekt_React#22]
- Route zu /login einbauen (OnClickEvent)
- bisher keine Änderung zu /login von /home oder ähnlichen
- keine Änderung in /login über OnClickEvent

**Comment by banu-i** [comment]
Login Formular mit Express und Datenbank verbunden.
User wird im Localstorage gespeichert.

- Redirect -> nach Anmeldung
- UseContext -> ändert Components - z.B.: SidebarStart und SidebarHome
