### ISSUE TITLE
/account Route

### ISSUE THREAD

**Issue by matze328** [matze328/Team1_Projekt_React#25]
- Route vom User zum Account setzen
- Route vom Footer zum Account setzen
- OnClick Funktionen 
- UseState bei "LoggedIn"

**Comment by banu-i** [comment]
/account Route aufgesetzt
mit UseState / onClick Event

Hier habe ich mich für ein Icon in der Sidebar entschieden, anstatt das der "Account" über User oder Footer erreichbar ist.
