### ISSUE TITLE
Navbar anpassen / LoggedIn+LogOut

### ISSUE THREAD

**Issue by SachsAlex** [matze328/Team1_Projekt_React#6]
- Suchleiste
- Navbar rechts! 
- Änderungen wenn man sicher erfolgreich angemeldet hat:

- SignUp zu LoggedIn
- LogIn zu LogOut

**Comment by banu-i** [comment]
UseContext "in Prozess". Umsetzung müsste noch durchgeführt werden.

- SignUp zu LoggedIn

- LogIn zu LogOut
