### ISSUE TITLE
Content / Music Player

### ISSUE THREAD

**Issue by matze328** [matze328/Team1_Projekt_React#9]
- Albumcover, Titel, Band, Album (eine div)
- Equalizer Grafik (erstmal nur statisch, nicht responsive) (eine div)
- Music Player (erstmal nur statisch, nicht responsive) (eine div)
- Lyrics (OnClickEvent -> ausklappen des Liedtextes nach unten); (OnClickEvent wiederholt -> einklappen) (eine div)

**Comment by SachsAlex** [comment]
- Albumcover nicht eingebaut (selten bei Royalty-Free-Music)
- Equalizer bleibt work-in-progress
- Lyrics bleibt work-in-progress (Royalty-Free-Music hat so gut wie nie Text)
